name: Mac

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'

jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            brew update
            brew instal automake autoconf libtool m4
            # ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
            # mpi
            brew install mpich
            # zlib
            brew install zlib     
        - name: Install HDF5
          run: |
            WORKDIR=$(pwd)
            rm -rf hdf5-1.13.0.tar.gz hdf5-1.13.0 ${WORKDIR}/.local/hdf5/1.13.0
            wget -qc https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.0/src/hdf5-1.13.0.tar.gz
            tar -zxf hdf5-1.13.0.tar.gz
            cd hdf5-1.13.0
            ./configure --prefix=${WORKDIR}/.local/hdf5/1.13.0 --disable-fortran \
                        --disable-hl --disable-tests --disable-tools \
                        --enable-parallel --enable-build-mode=production \
                        CC=mpicc CFLAGS="-O0 -g"
            make -j 4 install
        - name: Test log VOL
          run: |
            WORKDIR=$(pwd)
            autoreconf -i
            ./configure --with-hdf5=${WORKDIR}/.local/hdf5/1.13.0 --enable-shared \
                        CFLAGS="-O0 -g" CXXFLAGS="-O0 -g -std=c++14" LIBS=-lstdc++
            make -j 4 V=1
            make -j 4 V=1 tests
            # make check
            # make ptest
            # make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-hdf5=${WORKDIR}/.local/hdf5/1.13.0 --enable-shared CXXFLAGS='-O0 -g -std=c++14' LIBS=-lstdc++"
        - name: Print log
          if: ${{ failure() }}
          run: |
            WORKDIR=$(pwd)
            cat ${WORKDIR}/config.log
            cat ${WORKDIR}/tests/dynamic/test-suite.log
            cat ${WORKDIR}/tests/nc4/test-suite.log
            cat ${WORKDIR}/tests/basic/test-suite.log
            cat ${WORKDIR}/tests/testcases/test-suite.log
            cat ${WORKDIR}/examples/hdf5_examples/test-suite.log

