name: Ubuntu_openmpi

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get install automake autoconf libtool libtool-bin m4
            # mpi
            sudo apt-get install openmpi-bin
            # zlib
            sudo apt-get install zlib1g-dev
        - name: Install HDF5
          run: |
            WORKDIR=$(pwd)
            rm -rf hdf5-1.13.0.tar.gz hdf5-1.13.0 ${WORKDIR}/.local/hdf5
            wget -qc https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.0/src/hdf5-1.13.0.tar.gz
            tar -zxf hdf5-1.13.0.tar.gz
            cd hdf5-1.13.0
            ./configure --prefix=${WORKDIR}/.local/hdf5/1.13.0 --disable-fortran \
                        --disable-tests --disable-tools \
                        --enable-parallel --enable-build-mode=production CC=mpicc
            make -j 4 install
        - name: Install NetCDF
          run: |
            WORKDIR=$(pwd)
            rm -rf v4.7.4.tar.gz netcdf-c-4.7.4 ${WORKDIR}/.local/netcdf-c
            wget -qc https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.7.4.tar.gz
            tar -zxf v4.7.4.tar.gz
            cd netcdf-c-4.7.4
            ./configure --prefix=${WORKDIR}/.local/netcdf-c/4.7.4 --disable-dap \
                        CC=mpicc CPPFLAGS="-I${WORKDIR}/.local/hdf5/1.13.0/include" \
                        LDFLAGS="-L${WORKDIR}/.local/hdf5/1.13.0/lib" LIBS="-lhdf5"
            make -j 4 install
        - name: Test log VOL
          run: |
            WORKDIR=$(pwd)
            autoreconf -i
            ./configure --with-hdf5=${WORKDIR}/.local/hdf5/1.13.0 \
                        --enable-test-netcdf4=${WORKDIR}/.local/netcdf-c/4.7.4 \
                        --enable-test-openpmd \
                        --enable-test-hdf5-iotest \
                        TESTMPIRUN="mpiexec --oversubscribe -n NP"
            make V=1 -j 4
            make V=1 tests
            make check
            make ptest
            make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-hdf5=${WORKDIR}/.local/hdf5/1.13.0"
        - name: Print log
          if: ${{ failure() }}
          run: |
            WORKDIR=$(pwd)
            cat ${WORKDIR}/config.log
            cat ${WORKDIR}/tests/dynamic/test-suite.log
            cat ${WORKDIR}/tests/nc4/test-suite.log
            cat ${WORKDIR}/tests/basic/test-suite.log
            cat ${WORKDIR}/tests/testcases/test-suite.log
            cat ${WORKDIR}/tests/external/openpmd/test-suite.log
            cat ${WORKDIR}/tests/external/hdf5_iotest/test-suite.log
            cat ${WORKDIR}/examples/hdf5_examples/test-suite.log
            cat ${WORKDIR}/utils/h5lreplay/test.log
