name: Ubuntu_stack_vols

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
      - 'case_studies/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'case_studies/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get -y install automake autoconf libtool libtool-bin m4 cmake
            # The MPICH installed on github actions is too slow
            # sudo apt-get install mpich
            # mpicc -v
            # zlib
            sudo apt-get -y install zlib1g-dev
        - name: Build MPICH
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            rm -rf ${GITHUB_WORKSPACE}/MPICH
            mkdir ${GITHUB_WORKSPACE}/MPICH
            cd ${GITHUB_WORKSPACE}/MPICH
            wget -q https://www.mpich.org/static/downloads/4.0.2/mpich-4.0.2.tar.gz
            gzip -dc mpich-4.0.2.tar.gz | tar -xf -
            cd mpich-4.0.2
            ./configure --prefix=${GITHUB_WORKSPACE}/MPICH \
                        --silent \
                        --enable-romio \
                        --with-file-system=ufs \
                        --with-device=ch3:sock \
                        --disable-fortran \
                        CC=gcc
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
        - name: Install HDF5
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            rm -rf ${GITHUB_WORKSPACE}/HDF5
            mkdir ${GITHUB_WORKSPACE}/HDF5
            cd ${GITHUB_WORKSPACE}/HDF5
            VERSION=1.13.3
            wget -cq https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-${VERSION}/src/hdf5-${VERSION}.tar.gz
            tar -zxf hdf5-${VERSION}.tar.gz
            cd hdf5-${VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/HDF5 \
                        --silent \
                        --disable-fortran \
                        --disable-tests \
                        --enable-parallel \
                        --enable-threadsafe \
                        --enable-unsupported \
                        --enable-build-mode=production \
                        CC=${GITHUB_WORKSPACE}/MPICH/bin/mpicc
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
        - name: Install Argobots
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            ABT_DIR=${GITHUB_WORKSPACE}/Argobots
            rm -rf ${ABT_DIR}
            mkdir ${ABT_DIR}
            cd ${ABT_DIR}
            wget -qc https://github.com/pmodels/argobots/archive/refs/tags/v1.1.tar.gz
            tar -xf v1.1.tar.gz
            cd argobots-1.1
            ./autogen.sh
            ./configure --prefix=${ABT_DIR} \
                        --silent \
                        CC=${GITHUB_WORKSPACE}/MPICH/bin/mpicc \
                        CXX=${GITHUB_WORKSPACE}/MPICH/bin/mpicxx
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
        - name: Install Async VOL
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            export ABT_DIR=${GITHUB_WORKSPACE}/Argobots
            export HDF5_DIR=${GITHUB_WORKSPACE}/HDF5
            export ASYNC_DIR=${GITHUB_WORKSPACE}/Async
            export HDF5_ROOT=${HDF5_DIR}
            rm -rf ${ASYNC_DIR}
            mkdir ${ASYNC_DIR}
            cd ${ASYNC_DIR}
            wget -qc https://github.com/hpc-io/vol-async/archive/refs/tags/v1.4.tar.gz
            tar -xf v1.4.tar.gz
            cd vol-async-1.4
            mkdir build
            cd build
            CC=${GITHUB_WORKSPACE}/MPICH/bin/mpicc \
              CXX=${GITHUB_WORKSPACE}/MPICH/bin/mpicxx \
              cmake .. -DCMAKE_INSTALL_PREFIX=${ASYNC_DIR}
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            cd ${GITHUB_WORKSPACE}
        - name: Install Cache VOL
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            export ABT_DIR=${GITHUB_WORKSPACE}/Argobots
            export HDF5_DIR=${GITHUB_WORKSPACE}/HDF5
            export ASYNC_DIR=${GITHUB_WORKSPACE}/Async
            export CAHCE_DIR=${GITHUB_WORKSPACE}/Cache
            export HDF5_ROOT=${HDF5_DIR}
            rm -rf ${CAHCE_DIR}
            mkdir ${CAHCE_DIR}
            cd ${CAHCE_DIR}
            git clone https://github.com/hpc-io/vol-cache.git
            cd vol-cache
            mkdir build
            cd build
            export LD_LIBRARY_PATH="$ABT_DIR/lib:$LD_LIBRARY_PATH"
            CC=${GITHUB_WORKSPACE}/MPICH/bin/mpicc \
              CXX=${GITHUB_WORKSPACE}/MPICH/bin/mpicxx \
              HDF5_VOL_DIR=${ASYNC_DIR} \
              cmake .. -DCMAKE_INSTALL_PREFIX=${CAHCE_DIR}
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            cd ${GITHUB_WORKSPACE}
        - name: Build and test Log-layout based VOL
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            LOGVOL_DIR=${GITHUB_WORKSPACE}/log_vol_install
            autoreconf -i
            ./configure --with-hdf5=${GITHUB_WORKSPACE}/HDF5 \
                        --prefix=${LOGVOL_DIR} \
                        --with-mpi=${GITHUB_WORKSPACE}/MPICH \
                        --enable-test-threading \
                        --enable-test-env-vars
            # Do NOT test QMCPACK, as it requires FFTW which fails to build
            make -j 4 
            make install
            source ${LOGVOL_DIR}/bin/h5lenv.bash
            # Do NOT parallel build, cmake for external tests can fail
            make tests
            make check
            make ptest
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -j4 -s V=1 LIBTOOLFLAGS=--silent distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --with-hdf5=${GITHUB_WORKSPACE}/HDF5 --with-mpi=${GITHUB_WORKSPACE}/MPICH"
            cd ${GITHUB_WORKSPACE}
        - name: Test stacking Log VOL on top of Cache VOL only
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            cd ${GITHUB_WORKSPACE}/tests/passthru
            make clean
            make tests
            export ABT_DIR=${GITHUB_WORKSPACE}/Argobots
            export ASYNC_DIR=${GITHUB_WORKSPACE}/Async
            export CACHE_DIR=${GITHUB_WORKSPACE}/Cache
            export HDF5_DIR=${GITHUB_WORKSPACE}/HDF5
            export LOGVOL_DIR=${GITHUB_WORKSPACE}/log_vol_install
            export HDF5_ROOT=${HDF5_DIR}
            export HDF5_PLUGIN_PATH=${LOGVOL_DIR}/lib:${CACHE_DIR}/lib
            export LD_LIBRARY_PATH=${LOGVOL_DIR}/lib:${CACHE_DIR}/lib:${ASYNC_DIR}/lib:${ABT_DIR}/lib:${HDF5_DIR}/lib:${LD_LIBRARY_PATH}
            export HDF5_VOL_CONNECTOR="LOG under_vol=513;under_info={config=cache_1.cfg;under_vol=0;under_info={}}"
            make check
            make ptest
            cd ${GITHUB_WORKSPACE}/tests/basic
            cp ${GITHUB_WORKSPACE}/tests/passthru/cache_1.cfg .
            make clean
            make tests
            make check
            make ptest
            cd ${GITHUB_WORKSPACE}
        - name: Test stacking Log VOL on top of Cache and Async VOL
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            cd ${GITHUB_WORKSPACE}/tests/passthru
            make clean
            make tests
            export ABT_DIR=${GITHUB_WORKSPACE}/Argobots
            export ASYNC_DIR=${GITHUB_WORKSPACE}/Async
            export CACHE_DIR=${GITHUB_WORKSPACE}/Cache
            export HDF5_DIR=${GITHUB_WORKSPACE}/HDF5
            export LOGVOL_DIR=${GITHUB_WORKSPACE}/log_vol_install
            export HDF5_ROOT=${HDF5_DIR}
            export HDF5_PLUGIN_PATH=${LOGVOL_DIR}/lib:${CACHE_DIR}/lib:${ASYNC_DIR}/lib
            export LD_LIBRARY_PATH=${LOGVOL_DIR}/lib:${CACHE_DIR}/lib:${ASYNC_DIR}/lib:${ABT_DIR}/lib:${HDF5_DIR}/lib:${LD_LIBRARY_PATH}
            export HDF5_VOL_CONNECTOR="LOG under_vol=513;under_info={config=cache_1.cfg;under_vol=512;under_info={under_vol=0;under_info={}}}"
            make check
            make ptest
            cd ${GITHUB_WORKSPACE}/tests/basic
            cp ${GITHUB_WORKSPACE}/tests/passthru/cache_1.cfg .
            make clean
            make tests
            make check
            make ptest
            cd ${GITHUB_WORKSPACE}
        - name: Print log
          if: ${{ always() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            cat ${GITHUB_WORKSPACE}/config.log
            cat ${GITHUB_WORKSPACE}/tests/basic/*.log
            cat ${GITHUB_WORKSPACE}/tests/dynamic/*.log
            cat ${GITHUB_WORKSPACE}/tests/read_regular/*.log
            cat ${GITHUB_WORKSPACE}/tests/passthru/*.log
            cat ${GITHUB_WORKSPACE}/tests/testcases/*.log
            cat ${GITHUB_WORKSPACE}/examples/*.log
            cat ${GITHUB_WORKSPACE}/examples/hdf5_examples/*.log
            cat ${GITHUB_WORKSPACE}/utils/*/*.log

